# Setup
title:        Sajid's Notebook
tagline:      Here to keep day to day learning topics, both academic, professional and personal.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Sajid Hasan
  url:        https://linkedin.com/in/mdsajidhasan

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
