# Setup
title:        "Sajid's Notebook"
tagline:      
baseurl:      ""
paginate:     2
locale:       "en"

# About/contact
author:
  name:       Sajid Hasan
  url:        https://linkedin.com/in/mdsajidhasan

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
